version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=games

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: games
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql
    ports:
      - 3307:3306

volumes:
  mysql_data:
